# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Airspace Hugo"
license = "MIT"
licenselink = "https://github.com/karju-dev/airspace-hugo/LICENSE.md"
description = "Hugo porting for the Themefisher's Airspace theme"
homepage = "http://siteforthistheme.com/"
tags = []
features = []
min_version = 0.19

[author]
  name = "Giacomo Mariani"
  homepage = ""

# If porting an existing theme
[original]
  name = "airspace"
  homepage = "https://themefisher.com/products/airspace-free-bootstrap-website-template/"
  repo = "https://github.com/themefisher/airspace-free-html5-agency-template"
